spring:
  application:
    name: seata-client-provider-service #应用名称
  profiles:
    active: dev #开发环境
    #active: test #测试环境
    #active: pro #生产环境
  cloud:
    nacos:
      discovery: #nacos注册中心配置
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        namespace: public
        username: nacos
        password: nacos
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

server:
  servlet:
    context-path: /seata-client-provider #项目访问根路径

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ywstz.cloud.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

#seata配置
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server-service
      server-addr: 127.0.0.1:8848
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
