spring:
  application:
    name: spring-cloud-config-server-service #应用名称
  profiles:
    active: native,dev #开发环境
    #active: test #测试环境
    #active: pro #生产环境
  cloud:
    config: #config-server配置
      server:
        #        git: #git配置
        #          uri: https://github.com/ywstz/spring-cloud-config-server-file.git #git仓库地址
        #          search-paths:
        #            - spring-cloud-config-server-file
        native: #本地配置
          search-locations: file:D:/JavaWorkSpace/spring-cloud-example/spring-cloud-config-server-file/
  rabbitmq: #rabbitmq配置
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  servlet:
    context-path: /spring-cloud-config-server #项目访问根路径

#eureka-client配置
eureka:
  instance:
    instance-id: spring-cloud-config-server8093-service
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30     #eureka客户端像服务端发送心跳的时间间隔，默认30s
    lease-expiration-duration-in-seconds: 90     #eureka服务端在收到最后一次心跳后等待时间上限，默认90s，超时将剔除服务
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka8082.com:8082/spring-cloud-eureka-server/eureka,http://eureka8083.com:8083/spring-cloud-eureka-server/eureka


#暴露bus-refresh端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh