server:
  port: 8090 #项目访问端口号

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_example?serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: spring_cloud_example
    username: root
    password: 123456